te.ssh
~
~
~
~
01@DESKTOP-G1UECNQ MINGW64
~/OneDrive/Documentos/GitHub/meu-primeiro-projeto (main)
$
git pull --rebase origin main
git push
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 963 bytes | 50.00 KiB/s, done.
From github.com:lafemmegpsbrazil-ship-it/meu-primeiro-projeto
 * branch            main       -> FETCH_HEAD
    ebf90a5..15f89b4  main       -> origin/main
    Auto-merging teste.txt
    CONFLICT (content): Merge conflict in teste.txt
    error: could not apply 4c34817... Teste.ssh
    hint: Resolve all conflicts manually, mark them as resolved with
    hint: "git add/rm <conflicted_files>", then run "git rebase
    --continue".
    hint: You can instead skip this commit: run "git rebase --skip".
    hint: To abort and get back to the state before "git rebase", run
    "git rebase --
    abort".
    hint: Disable this message with "git config set advice.mergeConflict
    false"
    Could not apply 4c34817... # Teste.ssh
    fatal: You are not currently on a branch.
    To push the history leading to the current (detached HEAD)
    state now, use
    # with '#' will be ignored, and an empty message aborts the commit.
    #
    # interactive rebase in progress; onto 15f89b4
    # Last command done (1 command done):
    #    pick 4c34817 # Teste.ssh
    # Next command to do (1 remaining command):
    #    pick 5d5c57c # Testando SSH
    # You are currently rebasing branch 'main' on '15f89b4'.
    #
    # Changes to be committed:
    #       modified:   teste.txt
    #
    ~
    ~
    ~
    ~
    este.ssh

    # Conflicts:
    #       teste.txt

    # Please enter the commit message for your changes. Lines starting

    este.ssh

    este.ssh

    # Conflicts:
    #       teste.txt

    # Please enter the commit message for your changes. Lines starting
    # with '#' will be ignored, and an empty message aborts the commit.
    #
    # interactive rebase in progress; onto 15f89b4
    # Last command done (1 command done):
    #    pick 4c34817 # Teste.ssh
    # Next command to do (1 remaining command):
    #    pick 5d5c57c # Testando SSH
    # You are currently rebasing branch 'main' on '15f89b4'.
    #
    # Changes to be committed:
    #       modified:   teste.txt
    #

    ~